version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:floricky@db:5432/postgres

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: floricky
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
